language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      
  - "3.7"
  - "3.8"
before_install:
  - "pip install -U pip"
  - "python setup.py develop"
install:
  - pip install -r requirements.txt
script:
  - pytest