from .metod_with_classification import metod_class
from .check_classification_sd_metod import check_classification_sd_metod
from .regions_greater_than_2 import regions_greater_than_2
from .check_des_points import check_des_points
from .check_alg_cond_all_possibilities import check_alg_cond_all_possibilities
from .quad_obj_func import quad_function
from .quad_obj_func import quad_gradient
from .quad_obj_func import calc_minimizer_quad